# Generated by Django 3.0.7 on 2020-08-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200810_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
