# Generated by Django 3.0.7 on 2020-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200810_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='intrest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
