# Generated by Django 3.0.7 on 2020-08-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200817_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='intrest_rate',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=4),
        ),
    ]
